language: python

python:
  - "3.7"

script:
  - (cd examples/hello_world &&
         PYTHONPATH=../.. python -m pyfuzzer run hello_world hello_world.c &&
         PYTHONPATH=../.. python -m pyfuzzer corpus_print)
  - (cd examples/hello_world_custom_mutator &&
         PYTHONPATH=.:../..
             python -m pyfuzzer run -m hello_world_mutator.py hello_world hello_world.c &&
         PYTHONPATH=.:../.. python -m pyfuzzer corpus_print)
