language: python

python:
  - "3.7"

script:
  - (cd examples/hello_world &&
         env PYTHONPATH=../..
             python -m pyfuzzer hello_world hello_world.c)
  - (cd examples/hello_world_custom_mutator &&
         env PYTHONPATH=.:../..
             python -m pyfuzzer -m hello_world_mutator.py hello_world hello_world.c)
